run:
  go: '1.20'
  timeout: 10m

linters-settings:
  goimports:
    local-prefixes: "github.com/c0dered273/automation-remote-controller"
  gosimple:
    go: "1.20"
#  govet:
#    enable:
#      - fieldalignment

linters:
  enable:
    - contextcheck
    - depguard
    - gofmt
    - gosec
    - bidichk