name: "remote-control-client"
plc_uri: "modbus-tcp://10.0.1.10?unit-identifier=1&request-timeout=5000"

server_addr: "localhost:8080"
ca_cert: "cert/ca-cert.pem"
client_cert: "cert/client-cert.pem"

logger:
  level: "debug"
  caller: false
  format: "pretty"

devices:
  - device_id: "Lamp001"
    tag_address: "holding-register:1:WORD"
    values:
      SwitchON: 1
      SwitchOFF: 0

notifications:
  - tag_address: "holding-register:1:WORD/0"
    text:
      true: "Channel I0.0 active"
  - tag_address: "holding-register:1:WORD/1"
    text:
      true: "Channel I0.1 active"